# Generated by Django 2.2.7 on 2019-11-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclip',
            name='subtitle_text',
            field=models.CharField(max_length=300),
        ),
    ]
