# Generated by Django 3.0.5 on 2020-05-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20191130_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ActorFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.DecimalField(decimal_places=3, max_digits=6)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_in_frame', to='videos.Actor')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_clip_name', to='videos.VideoClip')),
            ],
        ),
    ]
