# Generated by Django 3.0.5 on 2020-05-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_actor_actorframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actorframe',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_clip_name', to='videos.Video'),
        ),
    ]
