# Generated by Django 3.0.5 on 2020-05-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20200509_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.DecimalField(decimal_places=3, max_digits=6)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_type_in_frame', to='videos.Actor')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='videos.Video')),
            ],
        ),
    ]
