# Generated by Django 3.0.5 on 2020-05-23 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_objectframe_objecttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectframe',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_type_in_frame', to='videos.ObjectType'),
        ),
    ]
