# Generated by Django 3.0.5 on 2020-05-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20200523_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='time_of',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
