# Generated by Django 3.0.5 on 2020-05-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_videoclip_time_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='items_found',
            field=models.CharField(default='', max_length=200),
        ),
    ]
