# Generated by Django 3.0.5 on 2020-06-16 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_videoclip_items_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='objectframe',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_video', to='videos.Video'),
        ),
        migrations.CreateModel(
            name='EmotionFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.DecimalField(decimal_places=3, max_digits=6)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_type', to='videos.Emotion')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_video', to='videos.Video')),
            ],
        ),
    ]
